### PR TITLE
Fix aria2 install location dependency

### PR DESCRIPTION
**Pull request by Joseph-DiGiovanni**
There's no reason to execute aria2c using a relative file path. If aria2 was installed correctly it should be accessible via the system PATH

### CODE REVIEW

**Comment by giantpinkrobots** [comment]
Not in Flatpak. In a Flatpak environment the user gets an "aria2c: command not found" error.

**Comment by Joseph-DiGiovanni** [comment]
Well there has to be a proper way to do this. Installing on a real arch system makes pkgdatadir /usr/local/share/varia, so it's looking for aria2 in the local directory. Wouldn't the correct relative location have bin before aria2?

**Comment by chrisawi** [comment]
> Not in Flatpak. In a Flatpak environment the user gets an "aria2c: command not found" error.

That's because you're installing it into `/app/aria2` instead of `/app/bin`, which is in PATH.

In the version of the manifest on Flathub, you can simply remove all of this and that should happen automatically:

			"no-make-install": true,
			"post-install": [
				"install -Dm755 src/aria2c -t /app/aria2/"
			],

flatpak-builder sets the install prefix to `/app` when you let it run the build.

**Comment by giantpinkrobots** [comment]
> > Not in Flatpak. In a Flatpak environment the user gets an "aria2c: command not found" error.
> 
> That's because you're installing it into `/app/aria2` instead of `/app/bin`, which is in PATH.
> 
> In the version of the manifest on Flathub, you can simply remove all of this and that should happen automatically:
> 
> 			"no-make-install": true,
> 			"post-install": [
> 				"install -Dm755 src/aria2c -t /app/aria2/"
> 			],
> 
> flatpak-builder sets the install prefix to `/app` when you let it run the build.

Huh. Didn't know that, will try it.

**Comment by Joseph-DiGiovanni** [comment]
Your change misses the point of my merge request and makes the issue even worse. Now unless aria2 AND the program are installed to /app/bin the launch script will not find either file.

**Comment by giantpinkrobots** [comment]
> Your change misses the point of my merge request and makes the issue even worse. Now unless aria2 AND the program are installed to /app/bin the launch script will not find either file.

Maybe I don't really know about the "proper" ways of doing things here... But do you think this could really be an issue? I mean, the Flatpak manifest will always install the dependencies on /app/bin.

**Comment by giantpinkrobots** [comment]
> > do you think this could really be an issue?
> 
> Yes. It breaks the ability to easily install on a real system outside of the flatpak environment. I understand flatpak is your main target here but needlessly breaking a normal install like this is pretty reckless

You're right, supporting installation outside Flatpak is actually something on my to-do list as it was recommended in an issue.

**Pull request merged**
